### ISSUE TITLE
The emulator won't run in Windows 10.

### ISSUE THREAD

**Issue by haris1309** [Lime3DS/Lime-3DS-Emulator#140] opened 2024-04-22 09:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Version 2110

### Description of Issue

I have downloaded both versions of the emulator and when I try to run the lime-qt.exe the window opens but the emulator won't respond.

### Expected Behavior

The emulator runs.

### Reproduction Steps

When I try to run lime-qt.exe the window opens but immediately it stops responding.

### Log File

I cannot generate a log file as the programm won't even run.

### System Configuration

CPU: AMD Ryzen 7 4800H with Radeon Graphics  2.90 GHz
GPU/Driver: NVIDIA GeForce GTX 1650 Ti/ Driver Version 552.22
RAM: 16.00 GB
OS: Windows 10

**Comment by rtiangha** [comment] 2024-04-24 13:47
Did it ever work under older Lime3DS releases? How about the last Citra nightly? Or even PabloMK7's fork?

**Comment by haris1309** [comment] 2024-04-24 14:03
The last Citra nightly worked very well before the Nintendo lawsuit after
that it stopped working. So I tried to download and run Lime3DS as an
alternative. I have never tried Lime 3DS before so I don't know.


Στις Τετ 24 Απρ 2024 στις 4:47 μ.μ., ο/η Reg Tiangha <
***@***.***> έγραψε:

**Comment by rtiangha** [comment] 2024-04-24 14:05
Can you try all the older Lime3DS releases and see if they still freeze? Lime3DS forked the Nightly branch, so perhaps it was a recent change that introduced a regression.

**Comment by haris1309** [comment] 2024-04-24 14:21
I will try that. Thank you.

Στις Τετ 24 Απρ 2024 στις 5:06 μ.μ., ο/η Reg Tiangha <
***@***.***> έγραψε:

**Comment by haris1309** [comment] 2024-04-24 19:49
After trying out all the versions available in GithHub, the problem seems
to consistently occur in every version. Do you have any more suggestions?

Στις Τετ 24 Απρ 2024 στις 5:06 μ.μ., ο/η Reg Tiangha <
***@***.***> έγραψε:

**Comment by rtiangha** [comment] 2024-04-24 19:58
Does it work with the last Citra Nightly?
https://archive.org/download/citra-2104-nightly

**Comment by Coderst1** [comment] 2024-04-27 18:51
This is probably due to outdated igpu drivers
Search for AMD Ryzen 7 4800H drivers and download them off of the official amd website and the issue should be fixed

**Comment by haris1309** [comment] 2024-04-27 20:22
Thank you after downloading the new drivers the emulator works.

Στις Σάβ 27 Απρ 2024 στις 9:52 μ.μ., ο/η Coderst1 ***@***.***>
έγραψε:

**Comment by Coderst1** [comment] 2024-04-27 20:27
Nice
You should go ahead and close this issue then

**Closed as completed** 2024-04-27 22:51 UTC
Labels: user error
