### ISSUE TITLE
External monitor support for lime3ds on android.

### ISSUE THREAD

**Issue by RageDeadworth** [Lime3DS/Lime-3DS-Emulator#376] opened 2024-08-19 21:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I am suggesting for external monitor support to be added to the android version of Lime 3ds similar to the already existing feature that exists for the Drastic emulator.

### Why would this feature be useful?

It would allow more customization and better gameplay experience for its users by allowing us to use external monitor attachments like the ones being sold by DNA gaming or, for already existing devices like the Rog phone 3 with the TwinView dock.
Given that the custom market for mobile/android 2nd screens is on the rise, I believe adding this feature will be synergistic for both drastic, it's users and 3rd party developers.
![i8h0vkuacor51](https://github.com/user-attachments/assets/33e1c6e9-158c-47c9-80f8-675c934012a4)

**Comment by OpenSauce04** [comment] 2024-08-20 11:49
Duplicate of #351

**Closed as completed by OpenSauce04** 2024-08-20 11:49 UTC
Labels: duplicate
