### ISSUE TITLE
Link for "user data" during Android app set up links to the defunct Citra Github page

### ISSUE THREAD

**Issue by vawgahan** [Lime3DS/Lime-3DS-Emulator#275] opened 2024-07-09 21:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2115

### Description of Issue

During the initial set up of the app on Android, when you get to the page that reads "Select User Folder" and "Select your user data directory with the button below.", the hyperlink on the text "user data" links to the defunct Citra Github (specifically https://github.com/citra-emu/citra/wiki/Citra-Android-user-data-and-storage)

### Expected Behavior

The link would lead to a newly made, up and running website or just provide the information in some way

### Reproduction Steps

Begin the set up process for the app
Reach the "Select User Folder" page
Click the hyperlink

### Log File

N/A

### System Configuration

Samsung Galaxy S20 FE 5G

**Comment by OpenSauce04** [comment] 2024-07-11 18:54
Turns out this and #279 were caused by the URL strings not having updated translations after they were changed, meaning that all non-english languages had outdated string content

**Comment by OpenSauce04** [comment] 2024-07-11 19:00
This will be addressed in the next update, thanks for the report

**Closed as completed by OpenSauce04** 2024-07-11 19:00 UTC
Labels: bug, good first issue, priority - high
