### ISSUE TITLE
Upscale with custom value (non-integer)

### ISSUE THREAD

**Issue by vitormmatos** [Lime3DS/Lime-3DS-Emulator#139] opened 2024-04-22 00:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

When choosing an upscale value, there could be an option to type a custom value.
This could include non-integers.

### Why would this feature be useful?

Example: When a 3x upscale produces slowdowns, but a 2x upscale runs fine.
Trying a value between both could still produce better graphics than a 2x upscaling and still a good performance.

**Comment by OpenSauce04** [comment] 2024-04-22 11:26
Duplicate of #115

**Closed as completed by OpenSauce04** 2024-04-22 11:26 UTC
Labels: duplicate
