### ISSUE TITLE
"Save Screenshots To" path still set to old (Citra) user data directory

### ISSUE THREAD

**Issue by karasuhebi** [Lime3DS/Lime-3DS-Emulator#307] opened 2024-07-23 23:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2116

### Description of Issue

The "Save Screenshots To" path is still set to the old (Citra) user data directory instead of the new one.

The only other reference I see to Citra is that the Username is still CITRA under the System settings.

### Expected Behavior

I expected the path to be changed to the new Lime3DS one.

### Reproduction Steps

Open Lime3DS 2116

### Log File

N/A

### System Configuration

N/A

**Comment by karasuhebi** [comment] 2024-07-24 01:41
I lied, there's more
![image](https://github.com/user-attachments/assets/c60565a4-66cd-4fb5-9493-e89ccb90dcde)

**Comment by rtiangha** [comment] 2024-07-25 16:34
Is there interest for a massive Citra->Lime3DS rename (in all the various case configurations) in the codebase? If so, I can take a day or two to do a massive sed/awk operation to rename everything (minus the user folder migration stuff) possibly this weekend. Let me know if that's something that people want.

Edit: Although it may break some things for users used to using Citra command line options to compile in their scripts (ex. CITRA_USE_PRECOMPILED_HEADERS would become LIME3DS_USE_PRECOMPILED_HEADERS) so people like distro package maintainers would need to be notified in advance somehow.

**Comment by OpenSauce04** [comment] 2024-07-25 16:41
> Is there interest for a massive Citra->Lime3DS rename (in all the various case configurations) in the codebase?

It's probably better to get something like that done sooner rather than later, so it would be a good idea to do so now.
I'm fine with it as long as you are careful with what you are find+replacing.

**Comment by rtiangha** [comment] 2024-07-25 16:44
Alright, I'll get to it when I can. Perhaps it should be done for the release after the upcoming one, and in the upcoming release notes, just add a warning that compile options will change in the next release so at least people who read it will get a heads up (although I guess they'll eventually learn the hard way when their compiles fail, lol).

**Comment by OpenSauce04** [comment] 2024-07-25 17:04
> ...Perhaps it should be done for the release after the upcoming one, and in the upcoming release notes, just add a warning...

Sounds good to me

**Comment by OpenSauce04** [comment] 2024-07-30 14:07
Forgot to come back to this and respond to the actual issue, but this is simply a case of a config being carried over to a newer version after the migration. There isn't anything that can be done to do this automatically, so you'll have to change the path yourself. New configurations have the correct path set.
I will be closing this as user error as it technically isn't the fault of the emulator itself, and is instead a side effect of the previously mentioned migration.

**Closed as completed** 2024-07-30 14:07 UTC
Labels: user error

**Comment by karasuhebi** [comment] 2024-07-30 14:23
An argument could be made that after seeing this message, a user reasonably expects for the Screenshots folder path to have been moved so I don't necessarily see that as user error.
![image](https://github.com/user-attachments/assets/aa5092ef-ca5b-451d-b606-fdaa54844bcd)

**Comment by OpenSauce04** [comment] 2024-07-30 15:41
The issue isn't that the screenshots folder wasn't moved, but it's instead that the path which is referenced in the Lime3DS configuration wasn't updated. As the `citra-emu` directory was the default value before the migration, this is where it will be set for people who have migrated. Those creating a new configuration will have the screenshots directory correctly pointed to the `lime3ds-emu` directory.

This cannot realistically be resolved without introducing horrifically hacky code. I will however mention this in the notes of the next update.

Closing this as "user error" is the closest thing to "this issue isn't technically the fault of the emulator itself but is instead a side effect of the end user's setup in a way which can't reasonably be addressed and will never happen again for future users".
