### ISSUE TITLE
Android: Allow for update on apk install

### ISSUE THREAD

**Issue by SpikyEchidna** [Lime3DS/Lime-3DS-Emulator#58] opened 2024-04-08 16:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

When trying to install the latest version of apk from github, the message "App not installed as package appears to be invalid" appears if you have the app installed. Uninstalling the app and then reinstalling the new apk is required, deleting the custom settings in the emulator.

### Why would this feature be useful?

Easy upgrade/downgrade for different versions without losing custom settings + ease of use in overall updating and installing.

**Comment by OpenSauce04** [comment] 2024-04-08 17:04
This issue has been fixed in a reupload of 2107. It was caused by the APK accidentally not being signed. Please redownload and reinstall the latest 2107 upload to ensure that you don't encounter the issue in the future

**Closed as completed** 2024-04-08 17:04 UTC
Labels: bug

**Comment by OpenSauce04** [comment] 2024-04-08 17:05
PS. You'll need to reinstall to install the fixed reuploaded version, but reinstalls won't be necessary in the future
