### ISSUE TITLE
Sleep Mode-StreetPass with Multiple Windows Instances

### ISSUE THREAD

**Issue by sp11111111** [Lime3DS/Lime-3DS-Emulator#318] opened 2024-07-31 11:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Could we have StreetPass support with multiple Lime3DS windows instances open at the same time with a keyboard button to put the emulators in 3DS Sleep Mode? OpenSauce04 said sleep mode isn’t implemented yet and he also said that you can’t get streetpass hits on lime3ds. Can this happen though? Why wouldn’t it be planned? It’s part of 3DS emulation?

### Why would this feature be useful?

It would be a useful feature as part of the full 3ds emulation.

**Comment by OpenSauce04** [comment] 2024-07-31 12:02
Duplicate of #314. Please don't open multiple issues for the same thing.

**Closed as completed** 2024-07-31 12:02 UTC
Labels: duplicate
