### ISSUE TITLE
(Android) Touch Button Overlay Saving and Loading and/or per-game button settings + allow sliding between all the buttons

### ISSUE THREAD

**Issue by fewfewfue** [Lime3DS/Lime-3DS-Emulator#301] opened 2024-07-19 20:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Title almost says it all, this option would essentially let you save the current position of your buttons on your overlay and also what buttons you have activated (like say, if a game doesn't necessarily use a button, it'd essentially be wasting touch space, so having the option to have it so the game you chose specifically to use the layout you've set WITHOUT changing it globally for every other game, and finally... having a sliding toggle for all buttons, not just the the d-pad

### Why would this feature be useful?

This could help people who want to play games with the touch buttons, and dont have a controller handy with them, it could make it so changing the overlay for better comfort of finger placement and just overall, especially regarding the Toggleable all button sliding, convenience.

**Comment by OpenSauce04** [comment] 2024-07-31 13:07
Partial duplicate of #254. Please make a seperate issue for the button sliding feature.

**Closed as completed by OpenSauce04** 2024-07-31 13:07 UTC
Labels: duplicate

**Comment by fewfewfue** [comment] 2024-07-31 13:33
Got it, my bad, ill do that!
