### ISSUE TITLE
(Android) portrait in landscape screen layout is broken

### ISSUE THREAD

**Issue by Coderst1** [Lime3DS/Lime-3DS-Emulator#223] opened 2024-05-28 01:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

2114

### Description of Issue

In portait on the landscape screen layout, the screens are messed up 
![Screenshot_20240527_213509_Lime3DS](https://github.com/Lime3DS/Lime3DS/assets/101987498/9edf4fc2-0e3f-4947-b514-364c832e99e1)

### Expected Behavior

The portait option should not be like this and instead be a big screen for the top and a little screen for bottom

Edit: It seems portrait and default were swapped as well, although maybe calling the default what you'd normally see on a 3ds is fine, and renaming portrait to large screen like its pc counterpart after the fix (just putting an idea out)

### Reproduction Steps

Go into any game and try the portrait option

### Log File

[lime3ds_log.old.txt](https://github.com/Lime3DS/Lime3DS/files/15462941/lime3ds_log.old.txt)

### System Configuration

All android devices

**Comment by Morningstar20009** [comment] 2024-05-28 02:34
hi on my android it indicates that there is a bug in the application and the games do not start

**Comment by OpenSauce04** [comment] 2024-05-28 09:14
I can replicate this issue. I will push out a hotfix as soon as I'm able to

Shame I didn't rotate my phone to landscape when testing the update last minute 🙃

I have a suspicion of how this happened

**Comment by OpenSauce04** [comment] 2024-05-28 11:13
I have discovered the cause of the issue
I am currently waiting on my laptop to slowly compile the emulator for testing before a release, as I am out of the house

**Comment by OpenSauce04** [comment] 2024-05-28 13:06
Fixed in ab99fff953755247abbff36d37c0e5a07c0916bc

**Closed as completed** 2024-05-28 13:06 UTC
Labels: bug, priority - urgent
