### ISSUE TITLE
Starfox 3DS Upside down Levels

### ISSUE THREAD

**Issue by NuelGFX** [Lime3DS/Lime-3DS-Emulator#466] opened 2024-09-24 22:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

all versions

### Description of Issue

Aquas, Solar, Andross levels are bugged and upside down. 

### Expected Behavior

level loads loads and the 3d scenery should be upright. 

### Reproduction Steps

can be reproduced when loading into those levels, bug is constant. 

### Log File

n/a

### System Configuration

CPU:snapdragon Gen 3
GPU/Driver:Adreno 750
RAM:12gb 
OS:android 14

**Comment by TheRealWario** [comment] 2024-09-25 00:22
duplicate of #52, you can simply leave a comment there if you want this to get more attention. For now, can you close this issue?

**Comment by NuelGFX** [comment] 2024-09-25 01:38
closing due to duplicate ticket.

**Closed as completed** 2024-09-25 01:38 UTC
Labels: bug
